### PR TITLE
remove experiments that fail to compile on new nightly

### PR DESCRIPTION
**Pull request by joonazan**
Removes the module "experiments" because nobody is using it and it breaks compilation.

### CODE REVIEW

**Review by shamatar — COMMENTED** [review]
Benchmarks depend on them, otherwise I'd remove them immediately

**Comment by joonazan** [comment]
In that case we can compile this module only for benchmarks, rather than having it be public and always compiled like now. Why do benchmarks need simd when the actual code doesn't, though?

**Comment by shamatar** [comment]
They do not, but baseline non-vectorized ops are there

**Comment by shamatar** [comment]
I disabled benchmarks in another PR, just use "main"

**Pull request closed without merging**
